### PR TITLE
Fix 114 Unclear/non-standard response for post api/v1/pit/pid

### LINKED ISSUE #114: Unclear/non-standard response for POST /api/v1/pit/pid
As described in the API docs, POST /api/v1/pit/pid may fail with status 409 or 500. It also says, that 409 is returned if validation fails and that more information can be found in the body. I've submitted the following (of course stupid) PID record:

```
{
    "pid": "sandboxed/12345",
    "record": [
        {
            "key": "test",
            "value": "value"
        },
        {
            "key": "test1",
            "value": "value1"
        }
    ]
}
```

As one could expect, HTTP 409 is returned, but without any information in the body or in the logs. I would suggest more expressive, fine-grained and standard compliant error code for this (very important) endpoint. My suggestion would be: 

Code | Description
------|---------------
201 (Created) | Creation successful.
400 (Bad Request) | If validation fails (details in body).
406 (Not Acceptable) | If provided input is invalid with regard to the supported content types.
409 (Conflict) | If providing an own PID is supported (seems not to be the case for now) 409 should indicate, that the PID already exists or in case of an update, if ETag comparison fails.
500 (Internal Server Error) | Only in case something unexpected happens in the Typed PID Maker. 
503 (Service Not Available) | If one of the related services (Handle.net or Type Registry) is not available.

Furthermore, as already written for HTTP 409 in the table, user-provided PIDs seem to be ignored at the moment. Probably, the server should respond in a proper way if the user provides an own PID. Maybe returning HTTP 501 (Not Implemented) as long as self-provided PIDs are not possible might be an idea here.

### PR DESCRIPTION
**Pull request by Pfeil**
This will change the API responses a little, making them more consistent. Merging and releasing these changes must result in a new major release. The PR is comparatively large because of a refactoring that has been postponed for some time, but is now necessary. The changes include an overall improved validation system, better errors (especially for validation), simplified and consistent APIs, better documentation and increased code coverage.

- [x] **Design more flexible validation strategy structure**
- [x] **Make use of it on create & validate**
- [x] Fix #114 
  - [x] Test: 201 created on successful creation:
    https://github.com/kit-data-manager/pit-service/blob/9f51d87395dce353175a387f86bc99877875746e/src/test/java/edu/kit/datamanager/pit/web/RestWithLocalPidSystemTest.java#L431
  - [x] Test: 400 on validation errors **with details in body** (with different issues in records)
    - Implementation: https://github.com/kit-data-manager/pit-service/pull/125/commits/ecef206d8e1f0eb8ada9b23b3b0fa3078bf22db6#diff-c84a84ccca36a22aa39ea8ff3ed594df2d34dc16f675ee19996e44d305bf4c83L13
    - Tests: (example) https://github.com/kit-data-manager/pit-service/pull/125/commits/ecef206d8e1f0eb8ada9b23b3b0fa3078bf22db6#diff-a611995f9031d8f10caea3eaf1ed9e8150899f129453a916429554360d7046c7L127
  - [x] Test: 415/406 on issues with given content/accept types: https://github.com/kit-data-manager/pit-service/pull/125/commits/4a03dea773b1b50a50d395656228b8dfc50765dc#diff-a06b401ed68f6d4a634622208d1ff88320b6caa2bdf9d9bdc73cabf4b9fa1b6b
  - [x] Test: 412/428/304/200 on ETAG comparison. (Consider https://www.baeldung.com/etags-for-rest-with-spring): https://github.com/kit-data-manager/pit-service/pull/125/commits/435807f45b47a0a89aca5a502d5c771cc8dc0337
  - [x] Test: 409 if an explicitly given PID already exists (might happen if we support custom PIDs soon) https://github.com/kit-data-manager/pit-service/pull/125/commits/906cac2ac776077bd2bd65ccf67793eba50d3e4c
  - [x] Impl: 500 on unexpected errors in the Typed PID Maker: Used Validation Exception (http 400) where applicable. https://github.com/kit-data-manager/pit-service/pull/125/commits/14fcecfb7ac7aace302dd9465919dff27fa94638
  - [x] Impl: 503 on unavailability of DTR or other external services we need to use.
  - [x] ~~Check if 409 should be applicable in more cases~~ does not seem to be the case
- [x] Wait for #128 and #127 to be merged, then merge master in here.
- [x] Update Documentation in javadoc / openapi with the correct/extended return codes.
- [x] double-check the error messages, e.g. from validation errors, are fully contained in the ~~body~~ response (message header). Currently, they are not. Here are some approaches which should solve this: https://www.baeldung.com/spring-response-status-exception
- [x] See if we still return the wrong error code (400/409) here and how we can change this: https://github.com/kit-data-manager/pit-service/issues/135 --> fixed, returns 500 now. We now have a class which can override exception to response conversion on the basis of the exceptions classes.
  - Seems like we need to catch `org.h2.jdbc.JdbcSQLDataException`, which is not thrown directly from our code, but in some background thread. It could be done using this Spring feature: https://www.baeldung.com/exception-handling-for-rest-with-spring#controlleradvice
  - To cause the issue for testing, in PidDatabaseObject change `@Column(length = $largeNumber)` to `@Column(length = 255)` and run the `createExtensiveRecord` test for the Local PID system. Remember master needs to be merged in beforehand (done), in order to get the required changes there.
-  [x] Remove HandleSystemRESTAdapter as we can not test it, and it is not fully implemented anyway. It may be added again in the future, but then with support for key/certificates only. Preferably with an official handle client implementation for the REST interface.
- [x] Include validation functionality for non-registered records into the POST request, using parameters
  - [x] Test
- [x] Include validation functionality for existing PIDs into the GET request, using parameters
  - [x] Test
- [x] Make sure they use the new validator implementations (adjust them or implement another one, if required).
- [x] Remove all replaced or not required APIs. Evaluate if the getProfile/downloadProfile endpoint makes sense and remove/adjust it, if required. Consider hiding it behind the GET request as a "getUrl/redirect to download location" functionality.
- [x] Make sure the old validation implementations are being removed. The previous points may make some code not necessary any more.
- [x] Check if there are missing tests for new APIs or parameters.

---

## Breaking changes/fixes

- Validation error changed from 409 to 400
- Inconsistencies are now considered a validation error and changed from 500 to 400 as above.
- Unavailable services are now indicated by 503 instead of the generic 500
- Etag implemented, breaking usage of update calls
- Removes legacy REST support for Handle until we have an implementation that supports certificates/keys
- (ongoing) validation endpoints will be included in post/get request as parameters, the old endpoints will be removed
- (ongoing) the profile download endpoint will be removed (and maybe come back in a more generic way for another endpoint using parameters

At least the ETag implementation can be considered a breaking change. Therefore, it will be added to the new major release milestone.

### CODE REVIEW

**Comment by Pfeil** [comment]
Before testing the other endpoints, I'd like to evaluate which ones we do actually need. As we have a new major release anyway, this would be a good point to remove (and add) new ones. This should happen with better validation tooling in mind. Some thoughts:

- (keep) **search** API for Elasticsearch (if enabled)
- (keep) **Resolve** the record of the given PID.
- (keep) **Update** an existing PID record
- (keep) **Create** a new PID record
- (keep) Check if the given PID **exists**.
- (keep) Return **known PIDs** (two endpoints)
- (remove) Resource matching type?
  - current documentation: "Check if a certain resource with a given PID is matching a type. The type is identified by its PID provided as path segment(s), whereas the resource is identified via its PID as request parameter."
  - currently basically does validation, which is handled using the functions below. Remove if other use stays unclear.
- (improve) **Get a profile** (resolve + redirect)
  - evolve to generic "getDownloadUrl(pid) ⇾ URL"?
- (improve) PID matching profile? (**validation**)
  - evolve to call like: validate(PID, optional-profile, optional-strategy)
  - if a profile is given, only check this profile. No matter if the profile is specified in the PID record. Else validate the record with its given profiles.
  - if strategy is given, use it. Else use the service default.
- (add) Validate hypothetical PID content against profile (**validate before registration** manually or even without the intention to register yet)
  - similar to validation above, but with record content which does not have to be registered yet.
  - like: validate(record-content, optional-profile, optional-strategy) ?

Two of the three points to change/remove have to do with validation. How would a proper validation rest interface look like? Currently, it is like this:

- HEAD /api/v1/pit/type/$profile_identifier
  - header "identifier" for PID to validate
  - intended function: deep validation against a single profile
  - implemented function: deep validation against a single profile, assuming to additional attributes allowed
- HEAD /api/v1/pit/profile/$profile_identifier
  - header "identifier" for PID to validate
  - intended function: "mandatory attributes are present" validation
  - implemented function: "mandatory attributes are present" validation

Analyse non-sound components in the current method:

- Is HEAD the right operation? "[The HEAD method asks for a response identical to a GET request, but without the response body.](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD)"
  - -> probably not
- does it make sense that /type means deep validation and /profile only checks for mandatory attributes?
  - I do not think so. In both cases, it is the profile being the entity: type/$profile-pid does not make a lot of sense.

How would a more REST-like interface for validation look like?

- For registered PIDs, this could be valid:
  - GET api/v1/pit/pid/**/validate
    - issue: not sure if we can make this /**/validate part
    - using headers for optional parameters like specific profile(s) or validation method(s)
    - like in the HATEOAS example on Wikipedia:
      ```
      "links": {
          "deposit": "/accounts/123abc/deposit",
          "withdraw": "/accounts/123abc/withdraw",
          "transfer": "/accounts/123abc/transfer",
          "close": "/accounts/123abc/close"
       }
      ```
    - This could replace all the current validation endpoints due to the flexibility with parameters.
- For content which is not (yet) registered, this could be valid:
  - POST api/v1/pit/validator
    - body for content to validate
    - using headers for optional parameters like specific profile(s) or validation method(s)

I did a small draft (parameters missing etc) of how this may look like on [swaggerhub](https://app.swaggerhub.com/apis/pfeil/PIT-Service/0.4).

**Comment by ThomasJejkal** [comment]
In my opinion, there is a certain conceptual conflict of using a RESTful interface to perform actions that are actually Remote Procedure Calls. Furthermore, using sub-endpoints like GET api/v1/pit/pid/**/validate for actions, that are actually used to access sub-resources in REST, may lead to some confusion. Also the approach of using HEAD controlling the result by request headers seems to be a bit too creative assuming that HEAD is just meant to be used to request resource-related information without transferring data, e.g., to obtain a resource's content length.

In my humble opinion I would utilize the POST endpoint including a request parameter, e.g., POST api/v1/pit/pid?dryrun=true (or something comparable) to allow using the create endpoint also in the validation-only scenario. Additional parameters may control the validation type, e.g., basic or deep. All other arguments, i.e., profile and digital object type, should be sent in the body the same way as a PID Record will be send in the create-scenario.

I'm also aware that you'll find articles which say, that POST should not require query parameters, but as they are optional I see not a huge problem here compared to the other options that are on the table.

**Comment by Pfeil** [comment]
> using sub-endpoints like GET api/v1/pit/pid/**/validate for actions, that are actually used to access sub-resources in REST, may lead to some confusion

I would not send a resource, I would simply trigger an action on an existing resource (the PID), similar to the HATEOAS example. All these examples are RPCs in some regard, aren't they?

> POST api/v1/pit/pid?dryrun=true (or something comparable)

I like it. The query parameter could also be a header (checking both), to satisfy those blog articles :). But it would only make sense to new records. What about validation of existing ones? Do people need to resolve it, or should they be able to resolve via PID? As this is the create endpoint, would validation fail if there is a PID given which is already registered? I can imagine this one, based on resolving, which could be handy for existing PIDs:

> GET api/v1/pit/pid/**?validation=true/strict/none(default)/$other (or something comparable)

While I like them, both kind of hide the validation capabilities behind the CRU~~D~~ ones. Is this desired?

**Comment by ThomasJejkal** [comment]
> I would not send a resource, I would simply trigger an action on an existing resource (the PID), similar to the HATEOAS example. All these examples are RPCs in some regard, aren't they?

True, I was just referring to the use of sub-paths in a URL. They typically point to sub-resources and not to functionalities. Functionalities I would rather address by query parameters (see last point)

> I like it. The query parameter could also be a header (checking both), to satisfy those blog articles :). But it would only make sense to new records. What about validation of existing ones? Do people need to resolve it, or should they be able to resolve via PID? As this is the create endpoint, would validation fail if there is a PID given which is already registered? I can imagine this one, based on resolving, which could be handy for existing PIDs:

Header would also be fine, but makes it harder to be included somewhere, e.g., only as link. If both options are supported, that's also fine, but you should be aware of conflicting parameters in header AND query.

> While I like them, both kind of hide the validation capabilities behind the CRU~D~ ones. Should I still go with it?

Well, as I said...to main focus of a RESTful interface is CRUD to documents aka. resources. Therefore, I would expect all functionality to be kind of hidden in request parameters, whereas the default remains the CRUD on resources.

**Comment by Pfeil** [comment]
Okay good. Sounds like a plan :). I'll see if I can somehow reasonably include the PID record in the error message somewhere (for the GET validation, at least). If this does not work, I'll check for other options.

**Comment by Pfeil** [comment]
Update: The responses are all fine using a rest client, but the mockMvc response bodies are empty if it is an error. So everything is working fine.

The pid-record is also included in the body response, but currently falsely serialized due to the optional type. Will fix this.

- [ ] fixed the record serialization in error cases

**Comment by Pfeil** [comment]
We are done :) The last commit somehow did not trigger the tests, so I triggered them manually here and everything looks good: https://github.com/kit-data-manager/pit-service/actions/runs/6131983116

**Pull request merged**
